# Not required to specifiy ipam dhcp, will be handled by panos
{{- range .Values.dp.networks }}
{{ if ne .name "ha2" }}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ template "dpName" $ }}-{{ .name }}
  namespace: kube-system
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "host-device",
      "pciBusID": {{ .pciBusID | quote }}
    }
{{- end }}
{{- end }}  
