{{ if .Values.common.ha }}
# For HA2 interface on MP-DP-1
# Update the static IP address and PCI ID of the HA2 interface
# add this to the net-attach list in pan-cn-ngfw-1.yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ template "dpName" . }}-ha-net-attach-1
  namespace: kube-system
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "host-device",
      {{- with (first .Values.dp.networks )}}
      "pciBusID": {{ .pciBusID | quote }},
      {{- end }}
      "ipam": {
         "type": "static",
         "addresses": [
          {
            {{- with (first .Values.dp.networks )}}
            "address": {{ .ip.fw1 | quote }}
            {{- end }}
         }
         ]
       }
    }
{{ end }}
