{{- if .Values.common.deploySharedResources }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mpName" . }}-secret
  namespace: kube-system
type: Opaque
stringData:
 # Panorama Auth Key
  PAN_PANORAMA_AUTH_KEY: {{ .Values.panorama.authKey | quote }}
  # Thermite Certificate retrieval 
  CN-SERIES-AUTO-REGISTRATION-PIN-ID: "<PIN Id>"
  CN-SERIES-AUTO-REGISTRATION-PIN-VALUE: "<PIN-Value>"
#Non-mandatory parameters
  # Uncomment this for CSP overide 
  #CN-SERIES-AUTO-REGISTRATION-API-CSP: "<csp-url>" 
{{ end }}
